### ISSUE TITLE
Make internals in Core and Lib public

### ISSUE THREAD

**Issue by jacobduijzer** [josdeweger-zz/SheetToObjects#42]
It is impossible to extend the library with new adapters unless it's done in the same codebase. The classes in both the core and lib project needed to create a new adapter should be public for better extendability.

**Comment by josdeweger-zz** [comment]
What classes would you need to have access to in your opinion?

**Comment by josdeweger-zz** [comment]
@jacobduijzer can I close this issue?

**Comment by jacobduijzer** [comment]
Guess so. I was trying to create the GoogleSheetProvicers as an external, additional package to extend the SheetToObjects package. Could be a nice feature but I do not really need it,
