### ISSUE TITLE
Protected Sheets as separate nuget package

### ISSUE THREAD

**Issue by jacobduijzer** [josdeweger-zz/SheetToObjects#45]
I think it would be better to create a separate package for the protected sheets because it uses different nuget packages as reference: especially the google packages, I would not want them in my project if I didn't use them. Either way for the Refit package, which is not used for the protected sheets.

Any comments on this?

**Comment by josdeweger-zz** [comment]
I completely missed this issue.

Good point, let me see what I can whip up

**Comment by josdeweger-zz** [comment]
See referenced PR. Something like that?
